version: "2"
services:
  app:
    container_name: app1
    restart: always
    image: app
    build: .
    ports:
      - "5000:5000"
    links:
      - mongo1
    command: "npm start"
    # environment:
    #   - MONGO_HOST="mongo1"
    #   - MONGO_PORT=27017
    #   - SERVER_PORT=5000
  mongo1:
    container_name: mongo1
    image: mongo:3.6
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

